Performance turning for default branch
edvakf/go-pploy pull request #9
Opened 2019-05-25 05:53 UTC by sue445

# Context
592ec167ac598258dc986139b0cca7f84c219fa4 is very slow, because `git remote show` is executed each view rendering :tired_face:

So I add caching

ref #8

# Architecture
* Add default branch cache (in memory)
* Use cache from view rendering
* Update cache after each `git checkout`

# Benchmark at project page
Using Chrome developer tool

![image](https://user-images.githubusercontent.com/608755/58365124-b4b20480-7efa-11e9-963c-bd3c6b284705.png)

## Before (v1.1.4)
* 1,950ms
* 2,440ms
* 1,970ms
* 3,150ms
* 2,040ms

## After (this PR)
* 2,030ms (1st),  2ms (2nd)
* 1,960ms (1st),  5ms (2nd)
* 1,950ms (1st),  2ms (2nd)
* 2,010ms (1st),  2ms (2nd)
* 3,290ms (1st),  2ms (2nd)

### remarks
1st is slow because branch is not cached, but 2nd is fast because branch is cached.

2019-05-27 02:09 UTC, edvakf commented on models/cache/default_branch_cache.go
> +	defaultBranchCache[project] = branch
pployでは現実的には問題にならないと思いますが、Goのmapはスレッドセーフではないという有名な話があり、インメモリキャッシュを作るときは `sync.Mutex` を使うか、Go 1.9からできた `sync.Map` を使うのが定石です。
https://qiita.com/ruiu/items/54f0dbdec0d48082a5b1
https://tanksuzuki.com/entries/golang-syncmap/

> Golangの並行処理では、共有リソースにアクセスする場合は競合が発生しないようにロックを用意する必要がある。 例えば、標準のmapはgoroutine safeではない。Write同士が競合した場合や、Write中のReadが発生するとPanicを起こしてしまう。

2019-05-27 02:14 UTC, edvakf commented on models/project/project.go
> +// Returns cached default branch if exists.
```suggestion
// GetCachedDefaultBranch returns cached default branch if exists.
```

> Comments should begin with the name of the thing being described and end in a period:

https://github.com/golang/go/wiki/CodeReviewComments#comment-sentences

2019-05-27 02:17 UTC, edvakf commented on models/project/project.go
> +// If default branch is not cached, get default branch from and save to cache.
```suggestion
// GetCachedDefaultBranch returns the default branch from memory if cached, otherwise, compute and cache it.
```

2019-05-27 02:23 UTC, edvakf requested changes

2019-05-27 02:23 UTC, edvakf commented on models/cache/default_branch_cache.go
> +// Get cached default branch
```suggestion
// GetDefaultBranch returns the default branch name in cache.
```

2019-05-27 02:23 UTC, edvakf commented on models/cache/default_branch_cache.go
> +// Set default branch to cache
```suggestion
// SetDefaultBranch caches the default branch name.
```

2019-05-27 02:23 UTC, edvakf commented on models/cache/default_branch_cache.go
> +// Delete default branch in cache
```suggestion
// DeleteDefaultBranch deletes the default branch cache entry.
```

2019-05-27 15:01 UTC, sue445 commented on models/cache/default_branch_cache.go
> +	defaultBranchCache[project] = branch
@edvakf Fixed at 9ad8c2b

2019-05-28 01:57 UTC, edvakf approved these changes

2019-05-28 01:58 UTC, merged

2019-05-28 01:58 UTC, edvakf commented on models/cache/default_branch_cache.go
> +	defaultBranchCache[project] = branch
Thank you!